sidebar:
    left:
        sticky: true
    right:
        sticky: true
widgets: 
    -
        position: right
        type: toc
        index: true
        collapsed: true
        depth: 3
    -
        position: right
        type: recent_posts
    -
        position: right
        type: categories
    -
        position: right
        type: archives
    -
        position: right
        type: tags
        order_by: name
        amount: 
        show_count: true